name: Transform

on: [push, pull_request]

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2'
      - run: dotnet tool install -g r2rml4net-cli
      - run: r2rml4net rml -c "${{ secrets.SQL_CONNECTION }}" -o triples.nq -m ./src-gen
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: triples.nq
