name: Transform

on: [push, pull_request]

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache ontop
        uses: actions/cache@v2
        env:
          cache-name: cache-mix-deps
        with:
          path: ./ontop-scripts/ontop
          key: ${{ runner.os }}-deps-${{ env.cache-name }}-${{ hashFiles('./ontop-scripts/convert.sh') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ env.cache-name }}-
            ${{ runner.os }}-deps-
            ${{ runner.os }}-
      - run: make
        env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: triples.nt
          path: ontop-scripts/triples.nt
