name: Transform

on: [push, pull_request]

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2'
      - uses: actions/setup-node@v1
      - run: dotnet tool install -g r2rml4net-cli
      - run: npm run transform -- -o triples.nq
        env:
          SQL_CONNECTION: ${{ secrets.SQL_CONNECTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: triples.nq
