name: Transform

on: [push, pull_request]

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - run: make
        env:
          SQL_URL: ${{ secrets.SQL_URL }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SPARQL_GRAPH_STORE: ${{ secrets.SPARQL_GRAPH_STORE }}
      - uses: actions/upload-artifact@v2
        with:
          name: triples.nt
          path: scripts/triples.nt
